const data={
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            category:"Shirt",
            image:'../p1.jpg',
            price:120,
            countInStock:10,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Adidas Slim Shirt',
            category:"Shirt",
            image:'../p2.jpg',
            price:200,
            countInStock:20,
            brand:'Adidas',
            rating:4,
            numReviews:15,
            description:'high quality product shirt',
        },
        {
            _id:'3',
            name:'Lacotes Slim Shirt',
            category:"Shirt",
            image:'../p3.jpg',
            price:220,
            countInStock:40,
            brand:'Nike',
            rating:3.5,
            numReviews:19,
            description:'high quality product crocodile',
        },
        {
            _id:'4',
            name:'Puma Slim Shirt',
            category:"Shirt",
            image:'../p4.jpg',
            price:205,
            countInStock:15,
            brand:'Puma',
            rating:4.8,
            numReviews:10,
            description:'high quality product puma',
        },
        {
            _id:'5',
            name:'Nike Slim Shirt',
            category:"Shirt",
            image:'../p1.jpg',
            price:120,
            countInStock:0,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'Nike Slim Shirt',
            category:"Shirt",
            image:'../p1.jpg',
            price:120,
            countInStock:100,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
    
    ]
}

export default data